project:
  type: website
  output-dir: docs

website:
  title: "Stephen Connor"
  site-url: https://sbconnor.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: outreach.qmd
        text: Outreach
      - href: knitting.qmd
        text: Knitting
    right:
      - icon: mastodon
        href: https://mathstodon.xyz/@stephenconnor
        target: _blank
      - icon: github
        href: https://github.com/sbconnor
        target: _blank
  page-footer: 
    right: Created with {{< iconify simple-icons:quarto>}} [Quarto](https://quarto.org/){target=_blank} and {{< iconify mdi:github>}} [GitHub](https://github.com/sbconnor/sbconnor.github.io){target=_blank}.

        
format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    page-layout: full

## Allow for \(...\) and \[..\]
from: markdown+tex_math_single_backslash