Another variant on conditioning^[[_NOT FOR PUBLICATION_ **(THIS IS INCOMPLETE)**]{.mark}] {#sec-variant}
===============================

Start with a \FreeInnovation as specified in @def-state-and-free-innovation.

The first step of the
required conditioning is based on an event of probability 
zero (namely that Poisson potential removals should
occur at specific times).
A rigorous approach to this uses
the initial step amounts to augmentation of the \FreeInnovation
by adding extra potential removals
at these times, with independent target marks distributed
uniformly over \(\{1, \ldots, \Population\}\).

The second step is to condition further the potential removals
and infections of the resulting augmented innovation by an event 
\(A(t_1,\ldots,t_\TotalRemovals)\), to the effect that the \activated removals
generated by the augmented innovation
are precisely those occurring at 
\(t_1{<\ldots<}t_\TotalRemovals\). 
Under the first-step conditioning, \(A(t_1,\ldots,t_\TotalRemovals)\) has positive probability;
if there are _no_ potential removals
other than those introduced above, then the \(r^\text{th}\)
introduced removal
is preceded almost immediately by a potential infection with target mark
\(r\) and infectee mark \(r{+}1\), with no other potential
infections.




It is convenient to introduce notation as follows:
for \(A\subset[0,\Duration)\) 
and patterns \(\InnovRem\) and \(\InnovInf\)
of removals and infections 
as described
in @def-state-and-free-innovation, let
\(\InnovRem(A)\),
respectively \(\InnovInf(A)\),
be the set of potential removals from \(\InnovRem\),
respectively potential infections from \(\InnovInf\),
with times in \(A\).

Informally the proof of the following @lem-conditioning and 
justification of the discussion in the
preceding paragraphs runs as follows.
Initially consider the case in which
the \activated removal times are
\(t_1{<\ldots<}t_\TotalRemovals\) in \((0,\Duration)\) (so conditioned removals all occur at positive times as \(t_i{>}0\)).
Set 
\(\delta_\text{max}=2\left(t_1\wedge(\Duration-t_\TotalRemovals) \wedge \min\{t_{i+1}-t_i: i = 1, \ldots k-1\}\right)\),
and for each positive \(\delta<\delta_\text{max}\) construct a family
\(\mathcal{I}_\delta\)
of \(k\) disjoint
open intervals of width \(\delta\) in \((0,\Duration)\), with \(t_i\) belonging to the \(i^\text{th}\) interval.
A simple example of \(\mathcal{I}_\delta\) is the collection of \(k\) open intervals
\((t_i{-}\tfrac{\delta}{2}, t_i{+}\tfrac{\delta}{2})\);
interval overlap and overspill being avoided because \(\delta<\delta_\text{max}\).


Let \((I_{0-}, \InnovRem, \InnovInf)\) be a \FreeInnovation
determining a free epidemic. 
Define
the _exterior \(\sigma\)-algebra_ \(\mathcal{G}^+_\delta\)
and _interior \(\sigma\)-algebra_ \(\mathcal{G}^-_\delta\) 
(collections of events generated respectively outside and
within the disjoint union of small open intervals \(\sqcup\mathcal{I}_\delta\))
by
\[\begin{aligned}
\mathcal{G}^+_\delta
\quad&=\quad
\sigma\left\{
I_{0-}, \InnovRem((0,\Duration)\setdiff\sqcup\mathcal{I}_\delta), 
\InnovInf((0,\Duration)\setdiff \sqcup\mathcal{I}_\delta)
\right\}\,,
\\
\mathcal{G}^-_\delta
\quad&=\quad
\sigma\left\{
\InnovRem(\sqcup\mathcal{I}_\delta), \InnovInf(\sqcup\mathcal{I}_\delta)
\right\}\,.
\end{aligned}\]

1. Consider the event \(E_\delta\in\mathcal{G}_\delta^-\) that at least one potential removal
(\activated or in\activated) lies
in each of the intervals of \(\mathcal{I}_\delta\).
Its probability is controlled by
\[
\Prob{E_\delta}\;=\;
\prod_{i=1}^k\left(1-e^{-(k-i+1)\beta\delta}\right)
\;>\; e^{-k\beta\delta} \delta^k \;\geq\; e^{-k\beta\delta_\text{max}} \delta^k \,.
\]

:::{.callout-tip}
### Here we use the simple estimates
a) \(1-e^{-(k-i+1)\beta\delta}>1-e^{-\beta\delta}\) for \(i=1,\ldots,k\) and \(\theta>0\),
b) and
\(1-e^{-\theta}-\theta e^{-\theta}=e^{-\theta}(e^{\theta}-1-\theta)>0\) for \(\theta>0\).
:::

2. Consider the \(\mathcal{G}_\delta^-\)-measurable event \(E^1_\delta\subset E_\delta\), 
corresponding to the additional requirement that there is never more than one potential incident (whether infection or removal) 
in any of the intervals of \(\mathcal{I}_\delta\).
Potential incidents with specified marks are generated by constant-rate Poisson processes, 
so the probability of \(E_\delta \setdiff E^1_\delta\) is controlled by
\[
\Prob{E_\delta \setdiff E^1_\delta}\quad\leq\quad
k \left(\prod_{i=1}^{k-1}\left(1-e^{-\gamma\delta}\right)\right)
\times
\left(1-e^{-\gamma\delta}-\gamma\delta e^{-\gamma\delta}\right)
\quad<\quad
\tfrac{k}{2} (\gamma\delta)^{k+1}\,,
\]
where
\(\gamma=\binom{\Population}{3}\alpha+\Population\beta\)
(see the computation of Equation (-eq-total-intensity)).

:::{.callout-tip}
### Here we use the simple estimates
a) \(1-e^{-\theta}<\theta\) if \(\theta>0\), 
b) and \(1-e^{-\theta}-\theta e^{-\theta}<\half\theta^2\) if \(\theta>0\).
:::

3. Recall that \(0<\delta<\delta_\text{max}\).
Conditional on \(E_\delta\) (at least one potential removal
in each interval), the conditional probability 
\(\Prob{E_\delta \setdiff E^1_\delta\;|\; E_\delta}=1-\Prob{E^1_\delta \;|\; E_\delta}\) is controlled by
\[
\Prob{E_\delta \setdiff E^1_\delta\;|\; E_\delta}
\quad\leq\quad
\frac{k \gamma^{k+1} \beta^k}{2} e^{k\beta\delta_\text{max}} \times \delta 
\quad=\quad C \, \delta\,.
\]
Thus, conditional on \(E_\delta\), for small \(\delta\), there is at least \(1-O(\delta)\) probability that each interval in
\(\mathcal{I}_\delta\) contains only a single potential removal and no potential infections. 

4. It follows that conditioning on \(E_\delta\) versus conditioning on \(E^1_\delta\)
produces conditional probability measures that are close in total variation metric.
Indeed, fix \(G\in\sigma\{\mathcal{G}_\delta^+, \mathcal{G}_\delta^-\}\).  
Working with \(\Prob{G\;|\; E_\delta}=
\Prob{G \cap E^1_\delta\;|\; E_\delta}+\Prob{G \setdiff E^1_\delta\;|\; E_\delta}\),
recalling \(E^1_\delta\subset E_\delta\) and using the elementary definition of conditional probability for events,
\[
\Prob{G\;|\; E_\delta}\quad=\quad
\Prob{G \;|\; E^1_\delta}\Prob{E^1_\delta\;|\; E_\delta}+\Prob{G \;|\; E_\delta\setdiff E^1_\delta}\Prob{E_\delta\setdiff E^1_\delta\;|\; E_\delta}\,,
\] 
Then control of \(\Prob{E_\delta\setdiff E^1_\delta\;|\; E_\delta}\) yields
\[
0\leq\Prob{G\;|\; E_\delta} - \Prob{G \;|\; E^1_\delta}\Prob{E^1_\delta\;|\; E_\delta}
\;=\;
\Prob{G \;|\; E_\delta\setdiff E^1_\delta}\Prob{E_\delta\setdiff E^1_\delta\;|\; E_\delta}
\leq C \, \delta\,.
\]
Likewise
\(0\leq \Prob{G \;|\; E^1_\delta} - \Prob{G \;|\; E^1_\delta} \Prob{E^1_\delta\;|\; E_\delta} \leq \Prob{E_\delta\setdiff E^1_\delta\;|\; E_\delta} \leq C \, \delta\),
hence
\[
|\Prob{G\;|\; E_\delta} - \Prob{G \;|\; E^1_\delta}| \quad\leq\quad C \, \delta\,.
\]
It follows that the total variation distance between the conditional probability measures
\(\Prob{\cdot\;|\;E_\delta}\)
and
\(\Prob{\cdot\;|\;E^1_\delta}\)
(both defined on \(\sigma\{\mathcal{G}_\delta^+, \mathcal{G}_\delta^-\}\))
is bounded above by \(C\,\delta\).  

5. Consider the \(\sigma\)-algebra \(\mathcal{F}_\delta\)
generated by \(\mathcal{G}^+_\delta\) and the target marks (but not times) of removals within the intervals of \(\mathcal{I}\).
Then \(\mathcal{F}_\delta\) is independent of the random variables which vanish off \(E^1_\delta\)
and otherwise are given by the times of the removals in the union of the intervals
(one removal per interval when \(E^1_\delta\) occurs).
Moreover consider the event which is the subset of \(E^1_\delta\) and indicates activation of all of the potential
removals in the union of intervals \(\sqcup\mathcal{I}_\delta\).
By the construction of @def-free-epidemic, this does not depend on the times of the removals in the union of the intervals
and is therefore conditionally independent of them given \(E^1_\delta\).
\newline
\textcolor{red}{The above paragraph is a bit wobbly!}

\textcolor{red}{Say something about infections are given by Poisson processes on restricted portions of timeline with restricted marks.}

Finally, if there is a conditioned removal at time \(0\) then in the limit this
is best achieved by ensuring \(I_{0-}>1\): as \(\delta\to0\) we find the probability
of infections being introduced between the relevant conditioned removal and time \(0\)
is relatively very small.


:::{.callout-caution}
### Include the possibility of \(t_1\) being equal to \(0\).
This is convenient if we want to analyze an epidemic from the time of the first (observed) removal.
:::
